# Usa a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Define variáveis de ambiente para configurar o banco de dados
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=satisfacao

# Expõe a porta padrão do PostgreSQL
EXPOSE 5432

