# Usa a imagem oficial mais recente do PostgreSQL como base
FROM postgres:latest

# Define o nome de usuário administrativo do banco de dados
ENV POSTGRES_USER=admin

# Define a senha do usuário administrativo
ENV POSTGRES_PASSWORD=admin_password

# Define o nome do banco de dados que será criado automaticamente na inicialização
ENV POSTGRES_DB=satisfaction_survey

# Expõe a porta padrão do PostgreSQL (5432) para permitir conexões externas
EXPOSE 5432

