version: '3.8'

services:
  # Serviço para o banco de dados PostgreSQL
  postgres:
    build: ./PostgreSQL
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: satisfaction_survey
    networks:
      - survey-network

  # Serviço para o banco de dados MongoDB
  mongodb:
    build: ./MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    networks:
      - survey-network

  # Serviço para a aplicação Node.js
  # nodejs:
  #   build: ./Node-app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - mongodb
  #   networks:
  #     - survey-network

  # Serviço para o exportador de métricas do PostgreSQL
  postgres-exporter:  
    build: ./postgres-exporter  
    environment:  
      DATA_SOURCE_NAME: "admin:admin_password@postgres:5432/satisfaction_survey"  # Corrigir string de conexão
    networks:
      - observability-network  
    ports:
      - "9187:9187"  

  # Serviço para o Prometheus
  prometheus:  
    build: ./Prometheus  
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    networks:
      - observability-network  
    ports:
      - "9090:9090"  

  # Serviço para o Grafana
  grafana:  
    build: ./Grafana  
    networks:
      - observability-network  
    ports:
      - "3000:3000"  

# Define as redes Docker
networks:
  survey-network:
    driver: bridge
  observability-network:
    driver: bridge
