# Usa uma imagem base do Node.js
FROM node:latest

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do seu projeto para o diretório de trabalho
COPY . /app

# Instala as dependências do projeto
RUN npm install

# Expõe a porta para o aplicativo Node.js
EXPOSE 3000

# Comando para iniciar o seu aplicativo Node.js
CMD ["npm", "start"]
