# Usa a imagem oficial mais recente do MongoDB como base
FROM mongo:latest

# Define variáveis de ambiente para configurar o usuário e senha administrativos do MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=adminpassword

# Expõe a porta padrão do MongoDB (27017) para permitir conexões externas
EXPOSE 27017

